# --- Cloudflare Section ---
- name: Run lego with Cloudflare domains
  ansible.builtin.shell: |
    lego --dns cloudflare \
         --email {{ letsencrypt_email }} \
         --accept-tos \
    {% for d in domains.cloudflare %}
      --domains {{ d | trim }} \
    {% endfor %}
         run
  environment:
    CLOUDFLARE_DNS_API_TOKEN: "{{ dns_provider.cloudflare.api_key }}"
    CLOUDFLARE_EMAIL: "{{ dns_provider.cloudflare.email }}"
  tags: get_ssl
  when: domains.cloudflare


# --- Arvan Section ---
- name: Run lego with Arvan domains
  ansible.builtin.shell: |
    lego --dns arvancloud \
         --email {{ letsencrypt_email }} \
         --accept-tos \
    {% for d in domains.arvan %}
      --domains {{ d | trim }} \
    {% endfor %}
         run
  environment:
    ARVANCLOUD_API_KEY: "{{ dns_provider.arvan.api_key }}"
  tags: get_ssl
  when: domains.arvan
